gem 'haml'
gem 'sass'
gem 'compass'
gem 'html5-boilerplate'

gem 'jquery-rails'
gem 'rails3-generators'
gem 'haml-rails'
gem 'meta_where'

gem 'hoptoad_notifier'

group :development, :test do
  gem 'ruby-debug'

  gem 'autotest-standalone'
  gem 'autotest-rails-pure'
  # gem 'autotest-fsevent', :require => false
  # gem 'autotest-growl', :require => false

  gem 'rspec-rails', '~> 2.5.0'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails', :require => false
  gem 'capybara'
  gem 'database_cleaner'
  gem 'spork', '~> 0.9.0.rc'
  gem 'launchy' # So you can do Then show me the page
  gem 'timecop'
  gem 'steak'
end

group :deployment do
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'capistrano_colors'
  # Contains bugs not fixed by author
  # gem 'dark-capistrano-recipes'
  # gem 'dark-capistrano-recipes', :git => 'git://github.com/daemon/capistrano-recipes.git'
end

group :console do
  gem 'wirble'
  gem 'hirb'
  gem 'awesome_print', :require => 'ap'
  gem 'looksee', :require => 'looksee'
end
